// react3/src/components/add-todo.component.tsx
import { Component, ChangeEvent } from "react";
import TutorialDataService from "../services/todo.service";
import ITutorialData from '../model/todo.model';
type Props = {};
type State = ITutorialData & {
  submitted: boolean
};
export default class AddTutorial extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.onChangeTitle = this.onChangeTitle.bind(this);
    this.onChangeDescription = this.onChangeDescription.bind(this);
    this.saveTutorial = this.saveTutorial.bind(this);
    this.newTutorial = this.newTutorial.bind(this);
    this.state = {
      id: null,
      title: "",
      description: "",
      submitted: false
    };
  }
  onChangeTitle(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      title: e.target.value
    });
  }
  onChangeDescription(e: ChangeEvent<HTMLInputElement>) {
    this.setState({
      description: e.target.value
    });
  }
  saveTutorial() {
    const data: ITutorialData = {
      title: this.state.title,
      description: this.state.description
    };
    TutorialDataService.create(data)
      .then((response: any) => {
        this.setState({
          id: response.data.id,
          title: response.data.title,
          description: response.data.description,
          submitted: true
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  newTutorial() {
    this.setState({
      id: null,
      title: "",
      description: "",
      submitted: false
    });
  }
  render() {
    const { submitted, title, description } = this.state;
    return (
      <div className="submit-form">
        {submitted ? (
          <div>
            <h4>ToDo was submitted successfully!</h4>
            <button className="btn btn-success" onClick={this.newTutorial}>
              Add
            </button>
          </div>
        ) : (
          <div>
            <div className="form-group">
              <label htmlFor="title">Title</label>
              <input
                type="text"
                className="form-control"
                id="title"
                required
                value={title}
                onChange={this.onChangeTitle}
                name="title"
              />
            </div>
            <div className="form-group">
              <label htmlFor="description">Description</label>
              <input
                type="text"
                className="form-control"
                id="description"
                required
                value={description}
                onChange={this.onChangeDescription}
                name="description"
              />
            </div>
            <button onClick={this.saveTutorial} className="btn btn-success">
              Submit
            </button>
          </div>
        )}
      </div>
    );
  }
}

// vuejs-crud/src/components/AddTodo.vue
<template>
  <div class="submit-form">
    <div v-if="!submitted">
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          required
          v-model="todo.title"
          name="title"
        />
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <input
          class="form-control"
          id="description"
          required
          v-model="todo.description"
          name="description"
        />
      </div>
      <button @click="saveTodo" class="btn btn-success">Submit</button>
    </div>
    <div v-else>
      <h4>Todo was submitted successfully!</h4>
      <button class="btn btn-success" @click="newTodo">Add</button>
    </div>
  </div>
</template>
<script>
import TodoService from "../services/TodoService";
export default {
  name: "add-todo",
  data() {
    return {
      todo: {
        id: null,
        title: "",
        description: "",
        
      },
      submitted: false
    };
  },
  methods: {
    saveTodo() {
      var data = {
        title: this.todo.title,
        description: this.todo.description
      };
      TodoService.create(data)
        .then(response => {
          this.todo.id = response.data.id;
          console.log(response.data);
          this.submitted = true;
        })
        .catch(e => {
          console.log(e);
        });
    },
    
    newTodo() {
      this.submitted = false;
      this.todo = {};
    }
  }
};
</script>
<style>
.submit-form {
  max-width: 400px;
  margin: auto;
  text-align: left;
}
</style>
