// react3/src/components/todos-list.component.tsx
import { Component, ChangeEvent } from "react";
import TodoService from "../services/todo.service";
import { Link } from "react-router-dom";
import ITodo from '../model/todo.model';
import { wait } from "@testing-library/user-event/dist/utils";
type Props = {};
type State = {
  todos: Array<ITodo>,
  currentTodo: ITodo | null,
  currentIndex: number,
  searchTitle: string
};
export default class TodosList extends Component<Props, State>{
  constructor(props: Props) {
    super(props);
    this.onChangeSearchTitle = this.onChangeSearchTitle.bind(this);
    this.retrieveTodos = this.retrieveTodos.bind(this);
    this.refreshList = this.refreshList.bind(this);
    this.setActiveTodo = this.setActiveTodo.bind(this);
    this.removeAllTodos = this.removeAllTodos.bind(this);
    this.searchTitle = this.searchTitle.bind(this);
    this.add10 = this.add10.bind(this);
    this.add100 = this.add100.bind(this);
    this.add1000 = this.add1000.bind(this);
    this.add3000 = this.add3000.bind(this);
    this.state = {
      todos: [],
      currentTodo: null,
      currentIndex: -1,
      searchTitle: ""
    };
  }
  componentDidMount() {
    this.retrieveTodos();
  }
  onChangeSearchTitle(e: ChangeEvent<HTMLInputElement>) {
    const searchTitle = e.target.value;
    this.setState({
      searchTitle: searchTitle
    });
  }
  retrieveTodos() {
    TodoService.getAll()
      .then((response: any) => {
        this.setState({
          todos: response.data
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
   refreshList() {
    this.retrieveTodos();
    this.setState({
      currentTodo: null,
      currentIndex: -1
    });
  }
  setActiveTodo(todo: ITodo, index: number) {
    this.setState({
      currentTodo: todo,
      currentIndex: index
    });
  }
  removeAllTodos() {
    TodoService.deleteAll()
      .then((response: any) => {
        console.log(response.data);
        this.refreshList();
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  add10() {
    TodoService.add10()
      .then((response: any) => {
        console.log(response.data);
        this.refreshList();
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  add100() {
    TodoService.add100()
      .then((response: any) => {
        console.log(response.data);
        this.refreshList();
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  add1000() {
    TodoService.add1000()
      .then((response: any) => {
        console.log(response.data);
        this.refreshList();
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  add3000() {
    TodoService.add3000()
      .then( (response: any) => {
        console.log(response.data);
        this.refreshList();
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  searchTitle() {
    this.setState({
      currentTodo: null,
      currentIndex: -1
    });
    TodoService.findByTitle(this.state.searchTitle)
      .then((response: any) => {
        this.setState({
          todos: response.data
        });
        console.log(response.data);
      })
      .catch((e: Error) => {
        console.log(e);
      });
  }
  render() {
    const {  todos, currentTodo, currentIndex } = this.state;
    return (
      <div className="list row">
           <button
            className="m-3 btn btn-sm btn-danger"
            onClick={this.removeAllTodos}
          >
            Remove All
          </button>
          <button
            className="m-3 btn btn-sm btn-warning"
            onClick={this.add10}
          >
            Add 10
          </button>
          <button
            className="m-3 btn btn-sm btn-warning"
            onClick={this.add100}
          >
            Add 100
          </button>
          <button
            className="m-3 btn btn-sm btn-warning"
            onClick={this.add1000}
          >
            Add 1000
          </button>
          <button
            className="m-3 btn btn-sm btn-warning"
            onClick={this.add3000}
          >
            Add 3000
          </button>
      
        <div className="col-md-6">
          <h4>ToDos List</h4>
          <ul className="list-group main-window">
            {todos &&
              todos.map((todo: ITodo, index: number) => (
                <li
                  className={
                    "list-group-item " +
                    (index === currentIndex ? "active" : "")
                  }
                  onClick={() => this.setActiveTodo(todo, index)}
                  key={index}
                >
                  {todo.title}
                </li>
              ))}
          </ul>
       
        </div>
        <div className="col-md-6">
          {currentTodo ? (
            <div>
              <h4>Todo</h4>
              <div>
                <label>
                  <strong>Title:</strong>
                </label>{" "}
                {currentTodo.title}
              </div>
              <div>
                <label>
                  <strong>Description:</strong>
                </label>{" "}
                {currentTodo.description}
              </div>
              
              <Link
                to={"/todos/" + currentTodo.id}
                className="badge badge-warning"
              >
                Edit
              </Link>
            </div>
          ) : (
            <div>
              <br />
              <p>Please click on chosen Todo...</p>
            </div>
          )}
        </div>
      </div>
    );
  }
}

// vuejs-crud/src/components/TodosList.vue
<template>
  <div class="list row">
<button class="m-3 btn btn-sm btn-danger" @click="removeAllTodos">
        Remove All
      </button>
       <button class="m-3 btn btn-sm btn-warning" @click="add10">
        Add 10
      </button>
       <button class="m-3 btn btn-sm btn-warning" @click="add100">
        Add 100
      </button>
       <button class="m-3 btn btn-sm btn-warning" @click="add1000">
        Add 1000
      </button>
       <button class="m-3 btn btn-sm btn-warning" @click="add3000">
        Add 3000
      </button>
    <div class="col-md-6 mt-5">
      <h4>ToDos List</h4>
      <ul class="list-group main-window">
        <li class="list-group-item"
          :class="{ active: index == currentIndex }"
          v-for="(todo, index) in todos"
          :key="index"
          @click="setActiveTodo(todo, index)"
        >
          {{ todo.title }}
        </li>
      </ul>
      
    </div>
    <div class="col-md-6 mt-5">
      <div v-if="currentTodo">
        <h4>Todo</h4>
        <div>
          <label><strong>Title:</strong></label> {{ currentTodo.title }}
        </div>
        <div>
          <label><strong>Description:</strong></label> {{ currentTodo.description }}
        </div>
        <router-link :to="'/todos/' + currentTodo.id" class="badge badge-warning">Edit</router-link>
      </div>
      <div v-else>
        <br />
        <p>Please click on chosen Todo...</p>
      </div>
    </div>
  </div>
</template>
<script>
import TodoService from "../services/TodoService";
export default {
  name: "todos-list",
  data() {
    return {
      todos: [],
      currentTodo: null,
      currentIndex: -1,
      title: ""
    };
  },
  methods: {
    retrieveTodos() {
      TodoService.getAll()
        .then(response => {
          this.todos = response.data;
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
    add10() {
      TodoService.add10()
        .then(response => {
         this.refreshList();
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
    add100() {
      TodoService.add100()
        .then(response => {
          this.refreshList();
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
    add1000() {
      TodoService.add1000()
        .then(response => {
          this.refreshList();
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
    add3000() {
      TodoService.add3000()
        .then(response => {
          this.refreshList();
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
    refreshList() {
      this.retrieveTodos();
      this.currentTodo = null;
      this.currentIndex = -1;
    },
    setActiveTodo(todo, index) {
      this.currentTodo = todo;
      this.currentIndex = todo ? index : -1;
    },
    removeAllTodos() {
      TodoService.deleteAll()
        .then(response => {
          console.log(response.data);
          this.refreshList();
        })
        .catch(e => {
          console.log(e);
        });
    },
    
    searchTitle() {
      TodoService.findByTitle(this.title)
        .then(response => {
          this.todos = response.data;
          this.setActiveTodo(null);
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    }
  },
  mounted() {
    this.retrieveTodos();
  }
};
</script>
<style>
.list {
  text-align: left;
  max-width: 750px;
  margin: auto;
}
.main-window {
  height: 800px;
  overflow: scroll;
}
</style>
