// vuejs-crud/src/components/TodosList.vue
<template>
  <div class="list row">
<button class="m-3 btn btn-sm btn-danger" @click="removeAllTodos">
        Remove All
      </button>
       <button class="m-3 btn btn-sm btn-warning" @click="add10">
        Add 10
      </button>
       <button class="m-3 btn btn-sm btn-warning" @click="add100">
        Add 100
      </button>
       <button class="m-3 btn btn-sm btn-warning" @click="add1000">
        Add 1000
      </button>
       <button class="m-3 btn btn-sm btn-warning" @click="add3000">
        Add 3000
      </button>
    <div class="col-md-6 mt-5">
      <h4>ToDos List</h4>
      <ul class="list-group main-window">
        <li class="list-group-item"
          :class="{ active: index == currentIndex }"
          v-for="(todo, index) in todos"
          :key="index"
          @click="setActiveTodo(todo, index)"
        >
          {{ todo.title }}
        </li>
      </ul>
      
    </div>
    <div class="col-md-6 mt-5">
      <div v-if="currentTodo">
        <h4>Todo</h4>
        <div>
          <label><strong>Title:</strong></label> {{ currentTodo.title }}
        </div>
        <div>
          <label><strong>Description:</strong></label> {{ currentTodo.description }}
        </div>
        <router-link :to="'/todos/' + currentTodo.id" class="badge badge-warning">Edit</router-link>
      </div>
      <div v-else>
        <br />
        <p>Please click on chosen Todo...</p>
      </div>
    </div>
  </div>
</template>
<script>
import TodoService from "../services/TodoService";
export default {
  name: "todos-list",
  data() {
    return {
      todos: [],
      currentTodo: null,
      currentIndex: -1,
      title: ""
    };
  },
  methods: {
    retrieveTodos() {
      TodoService.getAll()
        .then(response => {
          this.todos = response.data;
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
    add10() {
      TodoService.add10()
        .then(response => {
         this.refreshList();
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
    add100() {
      TodoService.add100()
        .then(response => {
          this.refreshList();
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
    add1000() {
      TodoService.add1000()
        .then(response => {
          this.refreshList();
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
    add3000() {
      TodoService.add3000()
        .then(response => {
          this.refreshList();
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
    refreshList() {
      this.retrieveTodos();
      this.currentTodo = null;
      this.currentIndex = -1;
    },
    setActiveTodo(todo, index) {
      this.currentTodo = todo;
      this.currentIndex = todo ? index : -1;
    },
    removeAllTodos() {
      TodoService.deleteAll()
        .then(response => {
          console.log(response.data);
          this.refreshList();
        })
        .catch(e => {
          console.log(e);
        });
    },
    
    searchTitle() {
      TodoService.findByTitle(this.title)
        .then(response => {
          this.todos = response.data;
          this.setActiveTodo(null);
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    }
  },
  mounted() {
    this.retrieveTodos();
  }
};
</script>
<style>
.list {
  text-align: left;
  max-width: 750px;
  margin: auto;
}
.main-window {
  height: 800px;
  overflow: scroll;
}
</style>

// angular3/src/app/components/todos-list/todos-list.component.ts
import { Component, OnInit } from '@angular/core';
import { Todo } from 'src/app/models/todo.model';
import { TodoService } from 'src/app/services/todo.service';

@Component({
  selector: 'app-todos-list',
  templateUrl: './todos-list.component.html',
  styleUrls: ['./todos-list.component.css']
})
export class TodoListComponent implements OnInit {

  todos?: Todo[];
  currentTodo: Todo = {};
  currentIndex = -1;
  title = '';

  constructor(private todoService: TodoService) { }

  ngOnInit(): void {
    this.retrieveTodos();
  }

  retrieveTodos(): void {
    this.todoService.getAll()
      .subscribe({
        next: (data) => {
          this.todos = data;
          console.log(data);
        },
        error: (e) => console.error(e)
      });
  }

  add10(): void {
    console.log("it works");
    this.todoService.addExtra().subscribe({
      next: (res) => {
        console.log(res);
        this.refreshList();
      },
      error: (e) => console.error(e)
    });

  }
  add100(): void {
    console.log("it works");
    this.todoService.addExtra100().subscribe({
      next: (res) => {
        console.log(res);
        this.refreshList();
      },
      error: (e) => console.error(e)
    });
  }
  add1000(): void {
    console.log("it works");
    this.todoService.addExtra1000().subscribe({
      next: (res) => {
        console.log(res);
        this.refreshList();
      },
      error: (e) => console.error(e)
    });
  }
  add3000(): void {
    console.log("it works");
    this.todoService.addExtra3000().subscribe({
      next: (res) => {
        console.log(res);
        this.refreshList();
      },
      error: (e) => console.error(e)
    });
  }

  refreshList(): void {
    this.retrieveTodos();
    this.currentTodo = {};
    this.currentIndex = -1;
  }

  setActiveTodo(todo: Todo, index: number): void {
    this.currentTodo = todo;
    this.currentIndex = index;
  }

  removeAllTodos(): void {
    this.todoService.deleteAll()
      .subscribe({
        next: (res) => {
          console.log(res);
          this.refreshList();
        },
        error: (e) => console.error(e)
      });
  }



}

<div class="list row">
  <button class="m-3 btn btn-sm btn-danger" (click)="removeAllTodos()">
    Remove All
  </button>
  <button class="m-3 btn btn-sm btn-warning" (click)="add10()">
    Add 10
  </button>
  <button class="m-3 btn btn-sm btn-warning" (click)="add100()">
    Add 100
  </button>
  <button class="m-3 btn btn-sm btn-warning" (click)="add1000()">
    Add 1000
  </button>
  <button class="m-3 btn btn-sm btn-warning" (click)="add3000()">
    Add 3000
  </button>
  <div class="col-md-6">
    <h4>ToDos List</h4>

    <ul class="list-group main-window">
      <li
        class="list-group-item"
        *ngFor="let todo of todos; let i = index"
        [class.active]="i == currentIndex"
        (click)="setActiveTodo(todo, i)"
      >
        {{ todo.title }}
      </li>
    </ul>


  </div>
  <div class="col-md-6">

    <app-todo-details
      [viewMode]="true"
      [currentTodo]="currentTodo"
    ></app-todo-details>
  </div>
</div>
