// vuejs-crud/src/components/TodoDetails.vue
<template>
  <div v-if="currentTodo" class="edit-form">
    <h4>ToDo</h4>
    <form>
      <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title"
          v-model="currentTodo.title"
        />
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <input type="text" class="form-control" id="description"
          v-model="currentTodo.description"
        />
      </div>
    </form>
    
    <button class="badge badge-danger mr-2"
      @click="deleteTodo"
    >
      Delete
    </button>
    <button type="submit" class="badge badge-success"
      @click="updateTodo"
    >
      Update
    </button>
    <p>{{ message }}</p>
  </div>
  <div v-else>
    <br />
    <p>Please click on chosen Todo...</p>
  </div>
</template>
<script>
import TodoService from "../services/TodoService";
export default {
  name: "todo",
  data() {
    return {
      currentTodo: null,
      message: ''
    };
  },
  methods: {
    getTodo(id) {
      TodoService.get(id)
        .then(response => {
          this.currentTodo = response.data;
          console.log(response.data);
        })
        .catch(e => {
          console.log(e);
        });
    },
   
    updateTodo() {
      TodoService.update(this.currentTodo.id, this.currentTodo)
        .then(response => {
          console.log(response.data);
          this.message = ' ToDo was updated successfully!';
        })
        .catch(e => {
          console.log(e);
        });
    },
    deleteTodo() {
      TodoService.delete(this.currentTodo.id)
        .then(response => {
          console.log(response.data);
          this.$router.push({ name: "todos" });
        })
        .catch(e => {
          console.log(e);
        });
    }
  },
  mounted() {
    this.message = '';
    this.getTodo(this.$route.params.id);
  }
};
</script>
<style>
.edit-form {
  text-align: left;
}
</style>

// angular3/src/app/components/todo-details/todo-details.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { TodoService } from 'src/app/services/todo.service';
import { ActivatedRoute, Router } from '@angular/router';
import { Todo } from 'src/app/models/todo.model';

@Component({
  selector: 'app-todo-details',
  templateUrl: './todo-details.component.html',
  styleUrls: ['./todo-details.component.css'],
})
export class TodoDetailsComponent implements OnInit {
  @Input() viewMode = false;

  @Input() currentTodo: Todo = {
    title: '',
    description: '',
  };

  message = '';

  constructor(
    private todoService: TodoService,
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    if (!this.viewMode) {
      this.message = '';
      this.getTodo(this.route.snapshot.params['id']);
    }
  }

  //get Todo with given id
  getTodo(id: string): void {
    this.todoService.get(id).subscribe({
      next: (data) => {
        this.currentTodo = data;
        console.log(data);
      },
      error: (e) => console.error(e),
    });
  }

  // Update Todo
  updateTodo(): void {
    this.message = '';
    this.todoService.update(this.currentTodo.id, this.currentTodo).subscribe({
      next: (res) => {
        console.log(res);
        this.message = res.message
          ? res.message
          : 'This ToDo was updated successfully!';
      },
      error: (e) => console.error(e),
    });
  }

  // Delete Todo with given id
  deleteTodo(): void {
    this.todoService.delete(this.currentTodo.id).subscribe({
      next: (res) => {
        console.log(res);
        this.router.navigate(['/todos']);
      },
      error: (e) => console.error(e),
    });
  }
}

<div *ngIf="viewMode; else editable">
  <div *ngIf="currentTodo.id">
    <h4>Angular TODO</h4>
    <div>
      <label><strong>Title:</strong></label> {{ currentTodo.title }}
    </div>
    <div>
      <label><strong>Description:</strong></label>
      {{ currentTodo.description }}
    </div>

    <a
      class="badge badge-warning"
      routerLink="/todos/{{ currentTodo.id }}"
    >
      Edit
    </a>
  </div>

  <div *ngIf="!currentTodo.id">
    <br />
    <p>Please click on chosen Todo...</p>
  </div>
</div>

<ng-template #editable>
  <div *ngIf="currentTodo.id" class="edit-form">
    <h4>ToDo</h4>
    <form>
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          class="form-control"
          id="title"
          [(ngModel)]="currentTodo.title"
          name="title"
        />
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <input
          type="text"
          class="form-control"
          id="description"
          [(ngModel)]="currentTodo.description"
          name="description"
        />
      </div>


    </form>


    <button class="badge badge-danger mr-2" (click)="deleteTodo()">
      Delete
    </button>

    <button
      type="submit"
      class="badge badge-success mb-2"
      (click)="updateTodo()"
    >
      Update
    </button>
    <p>{{ message }}</p>
  </div>

  <div *ngIf="!currentTodo.id">
    <br />
    <p>Cannot access this Todo ...</p>
  </div>
</ng-template>
